### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by KristerV** [davidlumley/concrete#3]
I promise i'm not a total noob, but I really don't understand how to use this thing. is the "Converting SASS/SCSS to CSS" part compulsory for getting it to work or is it optional for SASS fans?

Also do I need to clone all the files in this repo or just a few?

**Comment by davidlumley** [comment]
Hey @KristerV – sorry for the delay!

Basically you just need to grab the stuff from the CSS folder, hope that helps!
